### PR TITLE
Update for JupyterLab 3

### PR DESCRIPTION
**Pull request by nrbgt**
[Binder](https://mybinder.org/v2/gh/nrbgt/ipyelk/gh-6-lab3?urlpath=lab/tree/examples/08_Simulation_App.ipynb)

- [x] adds labextension to python distributions
- [x] adds lab dependency to pip 
- [x] uses `lumino`
- [x] removes third-party labextensions (toc is in core, widgets are from pip) 
- [x] updates robot tests
- [x] upgrade isort (and some other stuff, probably)
- [x] splits CI into a build/lint step on linux and test steps on various platforms
- [x] adds `bqplot >=0.12.20` to the demo/dev deps
  - [x] use `bqplot` on Simulation

### CODE REVIEW

**Comment by nrbgt** [comment]
We may want to tread carefully here, if we need want to land the other WIP PRs in a format that works with lab1...

**Comment by nrbgt** [comment]
Hooray :heavy_check_mark:

**Comment by nrbgt** [comment]
MacOS fail is _not_ what we're seeing on #60, just some cache fail nonsense

**Comment by nrbgt** [comment]
We back to green here.

**Review by dfreeman06 — APPROVED** [review]
Lab 3!

**Pull request merged**
